version: '3.4'

networks:
  dev:
    driver: bridge

services:
  netchallengetestapi:
    image: ${DOCKER_REGISTRY-}netchallengetestapi
    build:
      context: .
      dockerfile: NetChallengeTestAPI/Dockerfile
    depends_on:
      - "app_db"
    container_name: "netchallengetestapi"
    ports:
      - "8088:80"
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=app_db;Port=5432;Database=challengeDB;IntegratedSecurity=true;Pooling=true;
      - ASPNETCORE_URLS=https://+:443;http://+:80
    networks:
      - dev

  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=challengeDB
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev
volumes:
  app_data:    